dynamodb:
        image: rajatvig/dynalite-alpine
        ports:
          - '39000:8000'
##
datastore:
        image: 'mastodonc/kixi.datastore:latest'
        ports:
          - "38001:38001"
        volumes_from:
          - "dynamodb"
        volumes:
          - /tmp/kixi-datastore:/tmp/kixi-datastore
        links:
          - dynamodb:dynamodb
        environment:
          - CONFIG_PROFILE=local-kinesis
          - ZOOKEEPER=zookeeper
          - DYNAMODB=http://dynamodb:8000
          - COMMAND_STREAM=kixi-collect-dev-command
          - EVENT_STREAM=kixi-collect-dev-event
          - ENVIRONMENT=local-kinesis
          - VHOST=localhost
          - PORT=38001
        env_file:
          - aws-variables.env

mailer:
        image: 'mastodonc/kixi.mailer:latest'
        volumes_from:
          - "dynamodb"
        links:
          - dynamodb:dynamodb
        environment:
          - CONFIG_PROFILE=local
          - ENVIRONMENT=local
          - DYNAMODB=http://dynamodb:8000
          - COMMAND_STREAM=kixi-collect-dev-command
          - EVENT_STREAM=kixi-collect-dev-event
          - DRY_RUN=true
        env_file:
          - aws-variables.env
